echo off
md %1
copy zw.asm %1
copy ia.asm %1
copy mapa1.asm %1
copy mapa2.asm %1
copy mapa3.asm %1
copy graficas.asm %1
copy sprites.asm %1
copy aleato.asm %1
copy sonido.asm %1
copy musica.asm %1
copy historia.asm %1
copy mensajes.asm %1
copy retrato1.dat %1
copy retrato2.dat %1
copy retrato3.dat %1
copy retrato4.dat %1
copy retrato5.dat %1
copy retrato6.dat %1
copy retrato7.dat %1
copy retrato8.dat %1
copy retrato9.dat %1
copy retrato10.dat %1
copy retrato11.dat %1
copy retrato12.dat %1
copy retrato13.dat %1
copy titulo.dat %1
copy titulo2.dat %1
copy titulo3.dat %1
copy titulo4.dat %1
copy alerta.dat %1
copy alerta2.dat %1
copy edificio.dat %1
copy edifici2.dat %1
copy helicop.dat %1
copy fin.dat %1
copy fin2.dat %1
copy oscar.dat %1
copy adan.dat %1
copy zombnear.rom %1
copy zombnear.txt %1
echo respaldo hecho
