imagen graficas\logo.bmp     f:logo.bin      a b c d e
imagen graficas\paneleng.bmp f:paneleng.bin  a b c d e
imagen graficas\panelesp.bmp f:panelesp.bin  a b c d e
imagen graficas\titulo1.bmp  f:titulo1.bin   a b c d e
imagen graficas\titulo2.bmp  f:titulo2.bin   a b c d e
imagen graficas\titulo3.bmp  f:titulo3.bin   a b c d e
imagen graficas\copyrigh.bmp f:copyrigh.bin  a b c d e
imagen graficas\edificio.bmp f:edificio.bin  a b c d e
imagen graficas\compleng.bmp f:compleng.bin  a b c d e
imagen graficas\complesp.bmp f:complesp.bin  a b c d e
